module.exports = {
    DocumentType: {
        PRODUCT_IMG: 'PRODUCT_IMG',
        PRODUCT_SUPPLIER_LOGO: 'PRODUCT_SUPPLIER_LOGO',
        PRODUCT_GROUP_IMG: 'PRODUCT_GROUP_IMG'
    },
    ConfigurationKey: {
        PRICE_UPLIFT: 'PRICE_UPLIFT_PERCENTAGE',
        CURRENCY_USD_TO_UAH: 'CURRENCY_USD_TO_UAH',
        CURRENCY_USD_TO_UAH_SYNC_ENABLED: 'CURRENCY_USD_TO_UAH_SYNC_ENABLED',
        CURRENCY_USD_TO_UAH_SYNC_INTERVAL_MINUTES: 'CURRENCY_USD_TO_UAH_SYNC_INTERVAL_MINUTES',
    },
    Currency: {
        UAH: 'UAH',
        USD: 'USD'
    }
};