module.exports = {
    ConfigurationKey: {
        PRICE_UPLIFT: 'PRICE_UPLIFT_PERCENTAGE',
        CURRENCY_USD_TO_UAH: 'CURRENCY_USD_TO_UAH',
        CURRENCY_USD_TO_UAH_SYNC_ENABLED: 'CURRENCY_USD_TO_UAH_SYNC_ENABLED',
    },
};